x-laravel-app: &laravel-app
    build:
        context: .
        dockerfile: Dockerfile
        args:
            uid: ${WWWUSER:-1000}
            gid: ${WWWGROUP:-1000}
    env_file: .env
    restart: unless-stopped
    networks:
        - laravel

services:
    laravel_app:
        <<: *laravel-app
        container_name: laravel_app
        build:
            context: .
            target: dev
        user: "${WWWUSER:-1000}:${WWWGROUP:-1000}"
        volumes:
            - .:/var/www
        depends_on:
            - mysql
        profiles: ["dev"]

    scheduler:
        <<: *laravel-app
        container_name: laravel_scheduler
        build:
            context: .
            target: dev
        command: php artisan schedule:work
        volumes:
            - .:/var/www
        depends_on:
            - mysql
            - laravel_app
        profiles: ["dev"]

    nginx:
        image: nginx:1.27-alpine
        container_name: laravel_nginx
        ports:
            - "80:80"
        volumes:
            - .:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - laravel_app
        networks:
            - laravel
        profiles: ["dev"]

    mysql:
        image: mysql:8.1
        container_name: laravel_mysql
        command: --log-bin-trust-function-creators=1
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD_ROOT}
        volumes:
            - mysql_data:/var/lib/mysql
        ports:
            - "3307:3306"
        networks:
            - laravel
        profiles: ["dev", "prod"]

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: laravel_phpmyadmin
        environment:
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD_ROOT}
        ports:
            - "8081:80"
        depends_on:
            - mysql
        networks:
            - laravel
        profiles: ["dev"]

    laravel_prod:
        <<: *laravel-app
        container_name: laravel_prod
        build:
            context: .
            target: prod
        volumes:
            - storage_data:/var/www/storage
            - public_data:/var/www/public_shared
        depends_on:
            - mysql
        profiles: ["prod"]

    scheduler_prod:
        <<: *laravel-app
        container_name: laravel_scheduler_prod
        build:
            context: .
            target: prod
        command: php artisan schedule:work
        volumes:
            - storage_data:/var/www/storage
        depends_on:
            - mysql
            - laravel_prod
        profiles: [ "prod" ]

    nginx_prod:
        image: nginx:1.27-alpine
        container_name: laravel_nginx_prod
        ports:
            - "80:80"
        volumes:
            - ./docker/nginx/prod.conf:/etc/nginx/conf.d/default.conf
            - public_data:/var/www/public:ro
        depends_on:
            - laravel_prod
        networks:
            - laravel
        profiles: ["prod"]

networks:
    laravel:
        driver: bridge

volumes:
    mysql_data:
    storage_data:
    public_data:
